server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oh_coupon
    username: root
    password: 876010
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: debug

